### ISSUE TITLE
[질문] ECMAScript 개발자가 ECMAScript 를언어를 이용하여 직접 조작하는 값들의 타입이 바로 ECMAScript 언어 타입이다.

### ISSUE THREAD

**Issue by cozy60** [We-Don-t-Know-JS/ReadingBooks#2]
## 🔗 Reference
1장 - 타입(25P)

## ❓ 질문
> ECMAScript 개발자가 ECMAScript 를언어를 이용하여 직접 조작하는 값들의 타입이 바로 ECMAScript 언어 타입이다.

이 문장이 조금 이해가 가지 않아요!🤔  우리가 자바스크립트를 사용하면서 쓰는 변수내 값의 타입이 ECMAScript 언어 타입이라는 의미일까요?

**Comment by emthrology** [comment]
해당문장은 ecmaScript 문서의 일부를 번역한 것입니다. ecmaScript 에 대한 설명이라 보시면 됩니다. Javascript는 ecmaScript의 구현체 개념입니다.
